### ISSUE TITLE
Custom explosions bypass loggers

### ISSUE THREAD

**Issue by Pilvinen** [ExtendedAlpha/PluginBase#2]
Using the custom explosions will bypass block loggers (rollback will be impossible).

1)
fancy_explosions:
  tnt: true
  creeper: false
  enderdragon: false
  other: true
explosions:
  force_mult: 5.0
  yield_chance: 50
  prime_tnt: true

2) Install Prism or possibly some other block logging/rollback software
3) Place TNT
4) BOOM
5) The explosion/prime/etc events do not register -> Not possible to do a rollback.

This makes the BlockPhysics custom explosions features useless because it has infinite griefing potantial with no way for the admins or server owners to fight back.

Please try to find a way around this so that the event will get logged in custom explosions.

Here is the most excellent Prism that I'm using on my server. See API here to add support for it:
http://discover-prism.com/wiki/view/api/

**Comment by ExileDev** [comment]
I'll start working on a new update making prism as a soft dependence i'll let you know once the issue is fixed.
