### ISSUE TITLE
Issues with torches

### ISSUE THREAD

**Issue by Pilvinen** [ExtendedAlpha/PluginBase#4]
When a block falls on a torch the torch won't break and neither do the falling blocks. Instead they bounce up and down on the torch infinitely and lag the server.

Server: CraftBukkit version git-PaperSpigot-5be55c3-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Block Physics 1.3.0

Also about the new name, have you seen this: https://www.spigotmc.org/resources/block-physics.7862/

**Comment by ExileDev** [comment]
Hmm that should not be happening. I will start looking into this very soon to see if it's fixable.

Also yes I have seen Thinkofdeath resource and it how I got the idea to make this plugin.

**Comment by Pilvinen** [comment]
My point was that they have exactly the same name and use the same directory for their config.yml, but I suppose it's not a big deal since they conflict anyway.
