### ISSUE TITLE
fancy explosions throw chests around

### ISSUE THREAD

**Issue by Pilvinen** [ExtendedAlpha/PluginBase#5]
If you enable fancy explosions for TNT and put one right next to a chest to chest will fly in the air. Fancy explosions should not affect blocks with NBT data (which obviously doesn't get moved with the chest for example).

**Comment by ExileDev** [comment]
This is on purpose and is not something I will add. It works like this if there is nothing in the chest it will move, but if there is stuff in the chest it should blow up and get destroyed and all the items will fall to the ground.
